"""Repository service protocols."""

from __future__ import annotations

from typing import Protocol

from vibe.repository.models import RepositoryMetadata, RepositoryStatus, ValidationResult, WriteResult


class RepositoryOperations(Protocol):
    """Logical repository operations contract."""

    def initialize(self) -> None: ...

    def open(self, repository: str) -> RepositoryMetadata: ...

    def status(self) -> RepositoryStatus: ...

    def exists(self, path: str) -> bool: ...

    def read(self, path: str) -> str: ...

    def write(self, path: str, content: str) -> WriteResult: ...

    def list(self, path: str = ".") -> tuple[str, ...]: ...

    def metadata(self) -> RepositoryMetadata: ...

    def refresh(self) -> RepositoryMetadata: ...

    def health(self) -> object: ...

    def shutdown(self) -> None: ...
